### ISSUE TITLE
Incorrect dependencies

### ISSUE THREAD

**Issue by DManowitz** [conda-forge/geomstats-feedstock#3]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

This conda-forge has a number of differences in its dependencies as compared with the [upstream repo](https://github.com/geomstats/geomstats/blob/2.7.0/pyproject.toml).

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by ymontmarin** [comment]
Dependencies were updated during the  of the last version: https://github.com/conda-forge/geomstats-feedstock/pull/6
